Dockerfile
docker-entrypoint.sh
readme.md

Hi,
With this Pull Request we want to give you the option to add a badge to your README to show that
your software is available as an open web service in [Eyevinn Open Source Cloud](wwww.osaas.io).
With Eyevinn Open Source Cloud we turn open source into open web services and share the revenue
with the creators. 
Our goal with this platform is to reduce the barrier to get started with open source and contribute
to a sustainable business for open source by giving back a share of the revenue to the creators.
For our customers we can offer full code transparency and no vendor lock-in as all web services
are open source.
We want to *not be evil* and we do this to provide the creators with an additional
income stream for their projects.
Our pledge to the community is to:
- §1. Share revenue …

feat: enable in Eyevinn Open Source Cloud

---

package-lock.json
package.json
readme.md
src/config/config.ts
src/vast/vastApi.ts

This PR adds the original VAST XML as received from the adserver in the JSON response. If a client requests to receive XML instead a rewritten (proxied) VAST XML is returned. This will replace creative media files with the "normalized" ones if matched.
Also fixed so AD_SERVER_URL should contain the pathname as it cannot be assumed to be the same for all ad servers. This means that the AD_SERVER_URL=https://testadserver/api/v1/vast

feat(#4): rewrite VAST XML if requested XML response type

---

readme.md
src/util/time.ts
src/util/utils.test.ts
src/vast/vastApi.ts

When a client explicitly requests JSON by adding the header `accept: application/json`, the API responds with an asset list as defined by apple for HLS interstitials:
> The value of the X-ASSET-LIST is a quoted-string URL to a JSON object. The JSON object
must contain a key/value pair whose key is “ASSETS” and whose value is a JSON array of As-
set-Description JSON objects. (Note that keys in a JSON object are case-sensitive.) Each As-
set-Description JSON object MUST have a “URI” member whose value is a quoted-string abso-
lute URL for a single interstitial asset, and a DURATION member whose value is a decimal-float-
ing-point indicating the duration of the interstitial asset in seconds. The client is expected to
play the interstitial assets back-to-back in the order that they appear in …

feat: support for HLS interstitial asset lists

---

src/api.ts
src/config/config.ts
src/redis/redisclient.test.ts
src/redis/redisclient.ts
src/vast/vastApi.ts

Uses the redis key that is looked up in `partitionCreatives()` as a distributed lock in order to avoid multiple transcoding jobs being requested for the same asset. The lock has a TTL that can be set using the `IN_FLIGHT_TTL` environment variable, and defaults to 30 minutes. When the normalizer receives a notification from minio, it replaces the value with the (relative) URL to the master playlist, and persists the key in redis.

feat: use redis as lock to prevent assets being transcoded multiple times

---

src/encore/encoreclient.test.ts
src/vast/vastApi.ts

- replace for-loop in `replaceMediaFiles()` with a reduce that only pushes creatives with transcoded assets.
- remove an unused import

fix: creatives without transcoded assets are not included in the VAST response

---

src/vast/vastApi.ts

handles the case where a VAST response only contains one ad, which would previously lead to errors due to Array.reduce() not being a valid function

fix: error when vast only contains only one ad

---

jest.config.js
readme.md
src/api.ts
src/minio/minio.test.ts
src/minio/minio.ts
src/redis/redisclient.test.ts
src/vast/vastApi.ts
src/vmap/vmapApi.test.ts
src/vmap/vmapApi.ts

Intends to eventually resolve #20 
Adds basic VMAP fetching, parsing, and media file replacement functionality. Plus new unit tests.

feat: initial VMAP API implementation

---

src/vmap/vmapApi.test.ts
src/vmap/vmapApi.ts

PR has a quick fix for an issue with the VMAP interface. Field `vmap:VASTAdData` was missing. 
Vmap interface, getCreatives(), and unit tests for getCreatives() are corrected

fix: vmap interface and update tests

---

src/api.ts
src/config/config.test.ts
src/config/config.ts
src/encore/encoreclient.test.ts
src/encore/encoreclient.ts

Adds the ability to control which transcoding profile the ad normalizer will tell encore to use, based on the environment variable `ENCORE_PROFILE`. If this is not set, it defaults to `'program'`.

feat: configurable encore profile

---

src/config/config.ts
src/redis/redisclient.ts

- Fix an issue where we don't await the resolution of `zAdd` in `enqueuePackagingJob`, resulting in a dangling promise.

fix: dangling promise in redis client

---

src/encore/encoreclient.ts
src/encore/encoreservice.ts
src/redis/redisclient.test.ts
src/redis/redisclient.ts

- Add keepalive  to redis client
- Add reconnect strategy on dropped connection, wait 1 second then retry.
- Add error logging and try/catch for encore interactions that happen on job completion to try and diagnose errors observed in OSC

fix: keep redis collection alive

---

src/encore/encoreclient.test.ts
src/encore/encoreclient.ts

- Add fetch of SAT in `getEncoreJob`, and break the actual fetching into a separate method

fix: add service access token when fetching encore jobs in OSC

---

src/encore/encoreclient.ts
src/redis/redisclient.test.ts
src/redis/redisclient.ts

Since the `socket.keepAlive` setting did not fix the constant "socket closed unexpectedly" errors, we can try a different approach. By setting a ping interval, we might be able to keep the client connection alive.

fix: add ping interval to redis client

---

readme.md
src/api.ts
src/config/config.ts
src/packaging/packagingservice.test.ts
src/packaging/packagingservice.ts

At the moment, the normalizer has to guess where the packaged assets are.
There's a PR in the packager: https://github.com/Eyevinn/encore-packager/pull/14 to send the output path as part of a job success callback; the normalizer gets updated use this path to create the URLs.

fix: output path from packaging callback body

---

src/vast/vastApi.ts
src/vmap/vmapApi.test.ts
src/vmap/vmapApi.ts

If the header `X-Forwarded-For` is present in a request, it is passed along to the Ad server.
Fix incorrect header name for device user agent in the vmap endpoint
closes #46

feat: pass along forwaded-for value

---

src/vast/vastApi.ts
src/vmap/vmapApi.ts

Headers that are supposed to be passed on to the ad server (device user agent and forwarded for) didn't get propagated, due to the normalizer not realizing that the headers were present.
Seems like fastify sets all header keys as lowercase. By transforming the key strings to lowercase, we could verify that they were found.
After releasing and deploying, we should verify that these headers are now sent to the ad server.

fix: header keys should be lowercase

---

src/encore/encoreclient.test.ts
src/encore/encoreclient.ts
src/vast/vastApi.ts
src/vmap/vmapApi.test.ts
src/vmap/vmapApi.ts

Today, requests from the normalizer have the user agent `node` (default for nodejs); this can cause potential issues with some ad servers, as they might want to block requests from such generic user agents.
This PR sets the User agent header to eyevinn/ad-normalizer in order to mitigate this issue

feat: better user agent header

---

src/api.ts
src/config/config.test.ts
src/config/config.ts
src/redis/redisclient.test.ts
src/redis/redisclient.ts

- **feat: experimental redis cluster support**
To improve scalability and robustness, it is advisable to run redis/valkey in cluster mode with sharding; setting this up in the redis library is different from standalone mode. This PR adds support for conencting to redis clusters.
This PR adds the boolean field `clusterMode` to the Redis client class. This flag is controlled by the configuration (set the `REDIS_CLUSTER` env var to `true`).
If the client is in cluster mode, it will do all redis operations in a cluster-compatible way.

feat: support for redis clusters

---

src/util/string.test.ts
src/util/string.ts
src/vast/vastApi.ts
src/vmap/vmapApi.test.ts
src/vmap/vmapApi.ts

Adds support for cases where the caller may want to call a specific sub-domain on the ad server, f.ex. when a provider has multiple brands, or used by an aggregator provider.
Closes #55

feat: support subdomains on ad server

---

src/util/string.ts
src/util/utils.test.ts

With the way the normalizer currently works, there's a risk of running into issues with eventual consistency if content is re-encoded (f.ex. when the valkey is cleared due to a change in transcoding profiles).
If the same key already exists on the object storage, it _should_ be overwritten before the packager fetches the transcoded files, but depending on consistency guarantees, there _could_ be cases where an old transcoding output is packaged. This PR aims to solve that potential issue.
When constructing the output folder path, the normalizer appends a UUID to the folder structure. This ensures that each new transcode gets a separate output folder, eliminating overwrites and making sure we avoid issues with eventual consistency.
- **feat: use uuid subfolders to avoid problems with …

feat: use UUID subfolders to avoid problems with eventual consistency
